# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import integrations.models
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('flow', integrations.models.FlowField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAuth',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsCredentialModel',
            fields=[
                ('profileauth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.ProfileAuth')),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
            bases=('integrations.profileauth',),
        ),
    ]
