# -*- coding: utf-8 -*-
<< << << < HEAD: acumen_reports / projects / migrations / 0001_initial.py
# Generated by Django 1.11.10 on 2018-05-04 04:24
== == == =
# Generated by Django 1.11.10 on 2018-04-25 14:01
>>>>>> > 55a7487... add registration view, url, form and user model: acumen_reports / useraccounts / migrations / 0001_initial.py
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            name='ProjectReport',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('integration_type', models.CharField(choices=[
                 ('00', 'Google analytics'), ('01', 'Google search console')], default='00', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAuth',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='auth',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='projects.ProfileAuth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
