# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('integration_type', models.CharField(choices=[('00', 'Google analytics'), ('01', 'Google search console')], default='00', max_length=2)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.ProfileAuth')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.UserProject')),
            ],
        ),
    ]
